name: Push commit
on:
  release:
    types: [ created ]
  push:
    branches:
      - '*'

permissions:
  contents: write
  pages: write
  id-token: write


jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      artifact_url: ${{ steps.artifact.outputs.artifact_url }}

    env:
      UV_PYTHON: 3.11
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: uv sync --dev

      - name: Check formatting with Ruff
        run: ruff check

      - name: Build
        run: |
          if [[ '${{ github.event_name }}' = 'release' ]]; then
             sed -i -e "s/999.9.9.dev1/$GITHUB_REF_NAME/g" pyproject.toml
          else
            sed -i -e "s/999.9.9.dev1/999.9.9.dev$GITHUB_RUN_NUMBER/g" pyproject.toml
          fi
          uv build
          mkdir david8_build
          mv ./dist ./david8_build

      - name: Upload david8 package
        id: upload_dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: david8_build

      - name: Set artifact URL
        id: artifact
        run: |
          ARTIFACT_ID=${{ steps.upload_dist.outputs.artifact-id }}
          ARTIFACT_URL="https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$ARTIFACT_ID/zip"
          echo "artifact_url=$ARTIFACT_URL" >> $GITHUB_OUTPUT

  tests:
    runs-on: ubuntu-22.04
    permissions: write-all
    needs: [ build ]
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.11", "3.12", "3.13" ]

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            pyproject.toml
            uv.lock
            tests
            LICENSE

      - uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --dev

      - name: Download david8 dist
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Install david8 from dist
        run: uv pip install dist/$(ls ./dist/ | grep ".tar.gz")

      - name: Run tests with coverage. py${{ matrix.python-version }}
        run: |
          coverage run -m pytest
          coverage xml

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          format: cobertura
          file: coverage.xml
          parallel: true
          flag-name: py-${{ matrix.python-version }}

  coveralls_finish:
    needs: [ tests ]
    runs-on: ubuntu-22.04
    steps:
      - name: Finish Coveralls
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true

  trigger_postgres_dialect:
    needs: [ tests, build ]
    uses: ./.github/workflows/trigger_dialect_test.yml
    permissions: write-all
    with:
      repo: "d-ganchar/david8_postgresql"
      artifact_url: ${{ needs.build.outputs.artifact_url }}
    secrets:
      pat: ${{ secrets.DAVID8_CHANGES_TOKEN }}

  trigger_clickhouse_dialect:
    needs: [ tests, build ]
    uses: ./.github/workflows/trigger_dialect_test.yml
    permissions: write-all
    with:
      repo: "d-ganchar/david8_clickhouse"
      artifact_url: ${{ needs.build.outputs.artifact_url }}
    secrets:
      pat: ${{ secrets.DAVID8_CHANGES_TOKEN }}

  benchmarks:
    runs-on: ubuntu-22.04
    permissions: write-all
    needs: [ trigger_postgres_dialect, trigger_clickhouse_dialect ]
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.11", "3.12", "3.13" ]

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            pyproject.toml
            uv.lock
            benchmarks
            psrecord_reports
            psrecord_report.py
            LICENSE

      - uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --dev

      - name: Download david8 dist
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Install david8 from dist
        run: uv pip install dist/$(ls ./dist/ | grep ".tar.gz")

      - name: Benchmarks ${{ matrix.python-version }}
        run: |
          ORANGE='\033[38;5;208m'
          NC='\033[0m'
          echo -e "running benchmarks. rounds = ${ORANGE}20${NC}, iterations = ${ORANGE}1000${NC}"
          pytest --benchmark-only benchmarks/test_select_benchmarks.py --color=yes --benchmark-columns=min,max,mean,stddev,median,iqr,ops,outliers
          psrecord "python3 benchmarks/select_david8.py" --interval 0.001 --include-children > psrecord_reports/david8.txt 2>&1
          psrecord "python3 benchmarks/select_pypika.py" --interval 0.001 --include-children > psrecord_reports/pypika.txt 2>&1
          psrecord "python3 benchmarks/select_sqlalchemy.py" --interval 0.001 --include-children > psrecord_reports/sqlalchemy.txt 2>&1
          python psrecord_report.py
        env:
          TERM: xterm-256color
  

  publish_to_PyPi:
    runs-on: ubuntu-22.04
    needs: [ benchmarks ]
    if: github.event_name == 'release' && github.event.action == 'created'
    environment:
      name: pypi
      url: https://pypi.org/p/david8
    permissions:
      id-token: write
    steps:
      - name: Download david8 package
        uses: actions/download-artifact@v4
        with:
          name: dist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}